name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_TAG: andriiishcherbyna/laba4


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t $DOCKER_TAG .

    - name: Run tests in Docker container
      run: |
        docker run --rm $DOCKER_TAG test || exit 1

    - name: Run app in Docker container
      if: success()
      run: docker run -d -p 80:80 $DOCKER_TAG

    - name: Push Docker image to Docker Hub
      if: success()
      run: docker push $DOCKER_TAG

    - name: Test Failure
      if: failure()
      run: echo 'Build or tests failed'
